apiVersion: apps/v1
kind: Deployment


metadata:
  name: todo-auth

spec:
  replicas: 2

  selector:
    matchLabels:
      app: todo-auth
  template:
    metadata:
      labels:
        app: todo-auth
    spec:
      containers:
      - name: auth
        image: {{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}
        imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
        ports:
          - containerPort: 5002
        env:
          - name: PORT
            value: "5002"
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: MONGO_URI
          - name: JWT_SECRETE
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: JWT_SECRETE
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: tood-config
                key: NODE_ENV
        startupProbe:
          httpGet:
            path: /api/health
            port: 5002
          failureThreshold: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5002
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5002
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

---
apiVersion: v1
kind: Service

metadata:
  name: todo-auth
  labels:
    app: todo-auth

spec:
  selector:
    app: todo-auth
  ports:
    - name: http
      port: 5002
      targetPort: 5002
  type: ClusterIP


