apiVersion: apps/v1
kind: Deployment

metadata:
  name: todo-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: todo-backend

  template:
    metadata:
      labels:
        app: todo-backend

    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5001
          env: 
            - name: PORT
              value: "5001"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: MONGO_URI
            - name: JWT_SECRETE
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: JWT_SECRETE
            - name: LLM_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: LLM_SERVICE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: REDIS_URL
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: tood-config
                  key: NODE_ENV
            
          startupProbe:
            httpGet:
              path: /api/health
              port: 5001
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /api/health
              port: 5001
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5001
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi


---
apiVersion: v1
kind: Service

metadata:
  name: todo-backend
  labels:
    app: todo-backend

spec:
  selector:
    app: todo-backend
  ports:
    - name: http
      port: 5001
      targetPort: 5001
  type: ClusterIP