apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: todo-apps-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - todo-auth
          - todo-backend
          - todo-gateway
          - todo-llm
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
