apiVersion: v1
kind: Secret
metadata:
  name: todo-secret

type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb:27017/todoapp"
  JWT_SECRETE: "hello-234567890-!@#4567"
  VAPID_PRIVATE_KEY: "_DJiArS2OOBaXAmnCyCGXPqepU5j3BdEDNqwrG14MEQ"